---
layout: post
#标题配置
title:  彻底理解 promise
#时间配置
date:   2021-04-21 09:25:00 +0800
#大类配置
categories: es6 基础
#小类配置
tag: promise
---

* content
{:toc}

准备工作
====

同步回调
----
```js
const arr = [1,2,3];
arr.forEach(item => { // 遍历回调
    console.log(item);
})
console.log('回调之后');
```

异步回调
----

```js
setTimeout(()=>{ // 异步回调函数，会放入队列中后在执行
    console.log('timeout callback()');
}, 0);
console.log('setTimeout 之后');
```

js 常见内置错误
----

抛出错误：
1、 ReferenceError： 引用变量不存在，中断执行
2、 TypeError： 数据类型不存在
3、 RangeError：数据值不在其所允许的范围
4、 SyntaxError：语法错误

> 错误处理

1. 捕获错误：

```js
try{
    let d;
    console.log(d.xxx);
} catch (error){
    console.log(error.message);
    console.log(error.stack);
}
```

2. 抛出错误

```js
function something() {
    if(Date.now() % 2 === 1) {
        console.log('当前时间为基数');
    } else { // 自己决定错误，让下级去做处理
        throw new Error('当前时间为偶数，无法执行任务');
    }
}
try {
    something();
} catch (error) {
    console.log(error);
}
```

回调地狱解决方案
-----
1. promise.then()

但是由于 then() 需要等待 promise 的结果，所以这种实现方式不是最终极的解决方案。

2. async/await

终极解决方案，配合 promise 使用更佳。